apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloodapp-db
spec:
  serviceName: "bloodapp-db"
  replicas: 1
  selector:
    matchLabels:
      app: bloodapp-db
  template:
    metadata:
      labels:
        app: bloodapp-db
    spec:
      containers:
        - name: bloodapp-db
          image: arunkumarkoyyala/bloodbank:dbimage
          ports:
            - containerPort: 3306
          envFrom:
            - configMapKeyRef:
                name: bloodapp-config 
            - secretKeyRef:
                  name: bloodapp-secrets
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "256m"
          volumeMounts:
            - name: bloodapp-db-storage
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: bloodapp-db-storage
          persistentVolumeClaim:
            claimName: bloodapp-db-pvc